# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 07:19
from __future__ import unicode_literals

import definable_serializer.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_one', definable_serializer.models.fields.DefinableSerializerByYAMLField()),
                ('sample_two', definable_serializer.models.fields.DefinableSerializerByJSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
